#!/usr/bin/env bash

echo "Executing in $(pwd)"
echo "Command arguments: $*"

JAVAFX_EXTRA_ARGS="-Djava.awt.headless=true \
-Dtestfx.robot=glass \
-Dtestfx.headless=true \
-Dprism.order=sw \
-Dprism.text=t2k \
-Dtestfx.setup.timeout=10000"

MAVEN_COMMAND="mvn -f /root/build $* ${JAVAFX_EXTRA_ARGS}"

echo "Invoking \"${MAVEN_COMMAND}\""

bash -c "xvfb-run -a ${MAVEN_COMMAND}"
